version: "3"
services:
  node:
    container_name: "home_chat_node"
    image: "node:14"
    privileged: false
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "8081:8081"
    command: "node ./build/app.js"
    networks:
      - home_chat

networks:
  home_chat:
    external: true
